### ISSUE TITLE
fix: crash when completing japanese text

### ISSUE THREAD

**Issue by TorchedSammy** [Rosettea/Hilbish#209]
tried file completing some japanese text and it caused a panic. will post trace when I get home and can reproduce

**Comment by TorchedSammy** [comment]
this may or may not be related to #183

**Comment by TorchedSammy** [comment]
no its a different error, the problem is the readline library while #183 is sh interpreter
anyway, here is stack trace:
```
goroutine 1 [running]:
github.com/maxlandon/readline.(*Instance).viDeleteByAdjustVirtual(0xc000049000, 0xe)
	/home/sammy/Files/Projects/Hilbish/readline/tab-virtual.go:221 +0x265
github.com/maxlandon/readline.(*Instance).insertCandidateVirtual(0xc000049000, {0xc0003a0300, 0x4?, 0x4})
	/home/sammy/Files/Projects/Hilbish/readline/tab-virtual.go:29 +0x256
github.com/maxlandon/readline.(*Instance).updateVirtualComp(0xc000049000)
	/home/sammy/Files/Projects/Hilbish/readline/tab-virtual.go:111 +0x19d
github.com/maxlandon/readline.(*Instance).Readline(0xc000049000)
	/home/sammy/Files/Projects/Hilbish/readline/readline.go:320 +0xdb2
main.(*lineReader).Read(0xc00001ed50)
	/home/sammy/Files/Projects/Hilbish/rl.go:183 +0x65
main.main()
	/home/sammy/Files/Projects/Hilbish/main.go:176 +0xf59
```
