### ISSUE TITLE
panic when triggering tab completion in cd command

### ISSUE THREAD

**Issue by CelestialCrafter** [Rosettea/Hilbish#329]
hi! whenever i try to use tab completion on a `cd` command to a specific folder, hilbish panics.

example:
`cd /etc/nixos/mod<tab>` (panics when tab is pressed, it should instead autocomplete to modules)

for some reason this ONLY happens on my `/etc/nixos` folder.

i looked into `complete.go`, and its probably because `file` (ln 159) is nil because `os.ReadDir` is returning an unchecked error (ln 158) when reading `/etc/nixos`

trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8c52f4]

goroutine 1 [running]:
main.matchPath({0xc000529c40, 0x13})
	hilbish/complete.go:169 +0x254
main.fileComplete({0x828903?, 0xc000135400?}, {0xc0004459f8?, 0x0?}, {0x903e00?, 0xc000515ab0?, 0x0?})
	hilbish/complete.go:82 +0x47
main.hcmpFiles(0xc000188480, 0xc000135400)
	hilbish/complete.go:312 +0x39
github.com/arnodel/golua/runtime.(*GoCont).RunInThread(0xc000135400, 0xc000188480)
	github.com/arnodel/golua@v0.0.0-20230215163904-e0b5347eaaa1/runtime/gocont.go:103 +0xe4
github.com/arnodel/golua/runtime.(*Thread).RunContinuation(0xc000188480, {0xa0d0d0?, 0xc0001b19d0?})
	github.com/arnodel/golua@v0.0.0-20230215163904-e0b5347eaaa1/runtime/thread.go:98 +0x158
github.com/arnodel/golua/runtime.(*Thread).call(0xc000188480, {0xa07918?, 0xc0002c6240?}, {0xc0001f72a0, 0x2, 0x7f9625070988?}, {0xa0d088?, 0xc0001e2fc0?})
	github.com/arnodel/golua@v0.0.0-20230215163904-e0b5347eaaa1/runtime/thread.go:276 +0xd3
github.com/arnodel/golua/runtime.Call(0xc000529bc0?, {0x16?, {0x9479c0?, 0xc0002c6240?}}, {0xc0001f72a0?, 0xc0001f7278?, 0x60cf1d?}, {0xa0d088?, 0xc0001e2fc0?})
	github.com/arnodel/golua@v0.0.0-20230215163904-e0b5347eaaa1/runtime/lib.go:144 +0x26e
main.newLineReader.func6({0xc0004c5000, 0x16, 0x400}, 0x16, {0x92fb00?, {0x0?, 0xc000188480?}, 0xc000529ba0?})
	hilbish/rl.go:107 +0x2c5
github.com/maxlandon/readline.(*Instance).getCompletions(0xc00016e408)
	github.com/maxlandon/readline@v1.0.14/tab.go:195 +0x183
github.com/maxlandon/readline.(*Instance).getNormalCompletion(0xc00016e408)
	github.com/maxlandon/readline@v1.0.14/tab.go:148 +0x1c
github.com/maxlandon/readline.(*Instance).getTabCompletion(0xc00016e408?)
	github.com/maxlandon/readline@v1.0.14/tab.go:52 +0x66
github.com/maxlandon/readline.(*Instance).updateHelpers(0xc00016e408)
	github.com/maxlandon/readline@v1.0.14/update.go:20 +0x58
github.com/maxlandon/readline.(*Instance).insert(0xc00016e408?, {0xc0004459b0?, 0x6?, 0x7b31a6?})
	github.com/maxlandon/readline@v1.0.14/line.go:112 +0x2b0
github.com/maxlandon/readline.(*Instance).insertCandidate(0xc00016e408)
	github.com/maxlandon/readline@v1.0.14/tab-virtual.go:77 +0xc9
github.com/maxlandon/readline.(*Instance).Readline(0xc00016e408)
	github.com/maxlandon/readline@v1.0.14/readline.go:375 +0x10ba
main.(*lineReader).Read(0xc00011e9a0)
	hilbish/rl.go:197 +0x5c
main.main()
	hilbish/main.go:191 +0x1065
```

**Comment by TorchedSammy** [comment]
well the issue definitely isnt the ReadDir call, it's either `entry.Info` or `os.Lstat` erroring out and returning nil. either case, this shouldn't be happening at all.

can you edit the code to print file and error in both cases of line 161 and 165 and then post logs?

**Comment by CelestialCrafter** [comment]
```
info: &{.git 4096 2147484068 {877967354 63867510348 0xcb82a0} {66307 2097155 9 16804 0 0 0 0 4096 4096 8 {1717747337 481980851} {1731913548 877967354} {1731913548 877967354} [0 0 0]}}, <nil>
info: &{.gitignore 516 420 {52172606 63848057732 0xcb82a0} {66307 2097346 1 33188 0 0 0 0 516 4096 8 {1732222613 89296706} {1712460932 52172606} {1713392291 905752631} [0 0 0]}}, <nil>
info: &{LICENSE 1066 420 {52172606 63848057732 0xcb82a0} {66307 2097361 1 33188 0 0 0 0 1066 4096 8 {1732222613 91296780} {1712460932 52172606} {1713392293 631168718} [0 0 0]}}, <nil>
info: &{README.md 95 420 {802654011 63856523612 0xcb82a0} {66307 2097362 1 33188 0 0 0 0 95 4096 8 {1732222613 91296780} {1720926812 802654011} {1720926812 802654011} [0 0 0]}}, <nil>
info: &{cachix 4096 2147484068 {749951834 63867227319 0xcb82a0} {66307 2097364 2 16804 0 0 0 0 4096 4096 8 {1732222613 90296742} {1731630519 749951834} {1731630640 891231163} [0 0 0]}}, <nil>
info: &{cachix.nix 419 420 {674670596 63867227473 0xcb82a0} {66307 2097363 1 33188 0 0 0 0 419 4096 8 {1732222613 92296817} {1731630673 674670596} {1731630673 674670596} [0 0 0]}}, <nil>
info: &{flake.lock 11823 420 {863077263 63867499272 0xcb82a0} {66307 2097367 1 33188 0 0 0 0 11823 4096 24 {1732222613 90296742} {1731902472 863077263} {1731902472 863077263} [0 0 0]}}, <nil>
info: &{flake.nix 694 420 {825658604 63856523612 0xcb82a0} {66307 2098079 1 33188 0 0 0 0 694 4096 8 {1732222613 92296817} {1720926812 825658604} {1720926812 825658604} [0 0 0]}}, <nil>
info: &{hardware-configuration.nix 1893 420 {542332858 63867296398 0xcb82a0} {66307 2105859 1 33188 0 0 0 0 1893 4096 8 {1732196910 761283254} {1731699598 542332858} {1731699598 549333864} [0 0 0]}}, <nil>
info: &{home 4096 2147484068 {994461932 63867510360 0xcb82a0} {66307 2097370 2 16804 0 0 0 0 4096 4096 8 {1732222613 90296742} {1731913560 994461932} {1731913560 994461932} [0 0 0]}}, <nil>
info: &{modules 4096 2147484068 {221376756 63867820149 0xcb82a0} {66307 2622540 2 16804 0 0 0 0 4096 4096 8 {1732223351 563495374} {1732223349 221376756} {1732223349 221376756} [0 0 0]}}, <nil>
info: <nil>, lstat /etc/nixos/modules/awesome.nix: permission denied
```

`awesome.nix's` `ls -l` output
-rw-r--r-- 1 root root 416 Nov 17 23:21 awesome.nix
